development:
  adapter: postgresql
  encoding: unicode
  database: solar_deploy_test
  pool: 5
  username: gurudath
  password: gurudath

test:
  adapter: postgresql
  encoding: unicode
  database: solar_deploy_test
  pool: 5
  username: gurudath
  password: gurudath
production:
  adapter: postgresql
  encoding: unicode
  database: solar_deploy_test
  pool: 5
  username: gurudath
  password: gurudath
