development:
  adapter: postgresql
  encoding: unicode
  database: solar_deploy_test
  pool: 5
  username: postgres
  password: gurudath

test:
  adapter: postgresql
  encoding: unicode
  database: solar_deploy_test
  pool: 5
  username: postgres
  password: gurudath
